package cl.fiscalia.rgp.causapenal.model;

import org.kie.api.remote.Remotable;

/**
 * This class was automatically generated by the data modeler tool.
 */


@Remotable
public class Requerimiento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REQUERIMIENTO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REQUERIMIENTO_ID_SEQ", name = "REQUERIMIENTO_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.Boolean finSolicitarAntecedentes;

	private java.lang.String complejidad;

	private java.lang.Boolean requiereAntecedenteEspecifico;

	public Requerimiento() {}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getFinSolicitarAntecedentes() {
		return this.finSolicitarAntecedentes;
	}

	public void setFinSolicitarAntecedentes(
			java.lang.Boolean finSolicitarAntecedentes) {
		this.finSolicitarAntecedentes = finSolicitarAntecedentes;
	}

	public java.lang.String getComplejidad() {
		return this.complejidad;
	}

	public void setComplejidad(java.lang.String complejidad) {
		this.complejidad = complejidad;
	}

	public java.lang.Boolean getRequiereAntecedenteEspecifico() {
		return this.requiereAntecedenteEspecifico;
	}

	public void setRequiereAntecedenteEspecifico(
			java.lang.Boolean requiereAntecedenteEspecifico) {
		this.requiereAntecedenteEspecifico = requiereAntecedenteEspecifico;
	}

	public Requerimiento(java.lang.Long id,
			java.lang.Boolean finSolicitarAntecedentes,
			java.lang.String complejidad,
			java.lang.Boolean requiereAntecedenteEspecifico) {
		this.id = id;
		this.finSolicitarAntecedentes = finSolicitarAntecedentes;
		this.complejidad = complejidad;
		this.requiereAntecedenteEspecifico = requiereAntecedenteEspecifico;
	}

}